version: '2'
services:
  mysqldb:
        image: mysql:5.7       
        container_name: mysqldb        
        environment:
            MYSQL_DATABASE: subscription-adidasDB
            MYSQL_ROOT_PASSWORD: root
