server:
  port: 8005

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: subscriptionModule
          uri: lb://subscription-service
          predicates:
            - Path=/subscriptions/**